Combining RTMPErrors and ChangeTrackMuteRequests
100mslive/sample-app-android pull request #118
Opened 2021-10-07 06:16 UTC by Stuie

Fixes #115

RTMPError and ChangeTrackMuteRequests are now emitted via the same Flow, using a sealed Event class. The collection in MeetingFragment.kt has been updated accordingly.

This is intended as a preliminary PR. I have not tested the change yet, but before I spend a long time on testing, I wanted to make sure I had the right idea.

I also wanted to get some opinions on naming, as I suspect that `Event` is a little bit too generic. :)

2021-10-08 07:39 UTC, AniketSK commented
Thanks so much @Stuie, this is exactly what I'd imagined it should be. The naming is fine. I'll run a few tests on this myself and get back in a bit.

2021-10-20 10:14 UTC, AniketSK requested changes
Just the one change I suggested and opening the PR to dev instead of release-v2 and this should good! Thanks again @Stuie

2021-10-20 10:14 UTC, AniketSK commented on app/src/main/java/live/hms/app2/ui/meeting/MeetingFragment.kt
> +    lifecycleScope.launch {
The entire lifecycle of the fragment extends far beyond the view and I'd want this to be stopped as soon as the view is destroyed so it's important that the operations be carried out on the viewLifeCycleOwner.

```suggestion
    viewLifecycleOwner.lifecycleScope.launch {
```

2021-10-21 10:51 UTC, AniketSK approved these changes

2021-10-21 10:53 UTC, merged

2021-10-21 15:54 UTC, Stuie commented
Hey, sorry for not following up. I took a quick look last night, but I'm moving house right now and didn't have my dev machine set up to make the change you proposed.

2021-10-26 10:05 UTC, AniketSK commented
@Stuie

> Hey, sorry for not following up. I took a quick look last night, but I'm moving house right now and didn't have my dev machine set up to make the change you proposed.

Don't worry about it, the changes required were minor and I just made them. Thanks for contributing! Much appreciated.